/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AddEns {}
  interface AddEnsAttributes extends StencilHTMLAttributes {}

  interface DetailEnseignant {
    'match': MatchResults;
    'retour': RouterHistory;
  }
  interface DetailEnseignantAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
    'retour'?: RouterHistory;
  }

  interface DetailSearch {
    'match': MatchResults;
  }
  interface DetailSearchAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface SpiCandidat {}
  interface SpiCandidatAttributes extends StencilHTMLAttributes {}

  interface SpiFormation {}
  interface SpiFormationAttributes extends StencilHTMLAttributes {}

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiLogin {}
  interface SpiLoginAttributes extends StencilHTMLAttributes {}

  interface SpiPromotion {}
  interface SpiPromotionAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}

  interface SpiEnseignant {}
  interface SpiEnseignantAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AddEns': Components.AddEns;
    'DetailEnseignant': Components.DetailEnseignant;
    'DetailSearch': Components.DetailSearch;
    'SpiCandidat': Components.SpiCandidat;
    'SpiFormation': Components.SpiFormation;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiLogin': Components.SpiLogin;
    'SpiPromotion': Components.SpiPromotion;
    'SpiRoot': Components.SpiRoot;
    'SpiEnseignant': Components.SpiEnseignant;
  }

  interface StencilIntrinsicElements {
    'add-ens': Components.AddEnsAttributes;
    'detail-enseignant': Components.DetailEnseignantAttributes;
    'detail-search': Components.DetailSearchAttributes;
    'spi-candidat': Components.SpiCandidatAttributes;
    'spi-formation': Components.SpiFormationAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-login': Components.SpiLoginAttributes;
    'spi-promotion': Components.SpiPromotionAttributes;
    'spi-root': Components.SpiRootAttributes;
    'spi-enseignant': Components.SpiEnseignantAttributes;
  }


  interface HTMLAddEnsElement extends Components.AddEns, HTMLStencilElement {}
  var HTMLAddEnsElement: {
    prototype: HTMLAddEnsElement;
    new (): HTMLAddEnsElement;
  };

  interface HTMLDetailEnseignantElement extends Components.DetailEnseignant, HTMLStencilElement {}
  var HTMLDetailEnseignantElement: {
    prototype: HTMLDetailEnseignantElement;
    new (): HTMLDetailEnseignantElement;
  };

  interface HTMLDetailSearchElement extends Components.DetailSearch, HTMLStencilElement {}
  var HTMLDetailSearchElement: {
    prototype: HTMLDetailSearchElement;
    new (): HTMLDetailSearchElement;
  };

  interface HTMLSpiCandidatElement extends Components.SpiCandidat, HTMLStencilElement {}
  var HTMLSpiCandidatElement: {
    prototype: HTMLSpiCandidatElement;
    new (): HTMLSpiCandidatElement;
  };

  interface HTMLSpiFormationElement extends Components.SpiFormation, HTMLStencilElement {}
  var HTMLSpiFormationElement: {
    prototype: HTMLSpiFormationElement;
    new (): HTMLSpiFormationElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiLoginElement extends Components.SpiLogin, HTMLStencilElement {}
  var HTMLSpiLoginElement: {
    prototype: HTMLSpiLoginElement;
    new (): HTMLSpiLoginElement;
  };

  interface HTMLSpiPromotionElement extends Components.SpiPromotion, HTMLStencilElement {}
  var HTMLSpiPromotionElement: {
    prototype: HTMLSpiPromotionElement;
    new (): HTMLSpiPromotionElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLSpiEnseignantElement extends Components.SpiEnseignant, HTMLStencilElement {}
  var HTMLSpiEnseignantElement: {
    prototype: HTMLSpiEnseignantElement;
    new (): HTMLSpiEnseignantElement;
  };

  interface HTMLElementTagNameMap {
    'add-ens': HTMLAddEnsElement
    'detail-enseignant': HTMLDetailEnseignantElement
    'detail-search': HTMLDetailSearchElement
    'spi-candidat': HTMLSpiCandidatElement
    'spi-formation': HTMLSpiFormationElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-login': HTMLSpiLoginElement
    'spi-promotion': HTMLSpiPromotionElement
    'spi-root': HTMLSpiRootElement
    'spi-enseignant': HTMLSpiEnseignantElement
  }

  interface ElementTagNameMap {
    'add-ens': HTMLAddEnsElement;
    'detail-enseignant': HTMLDetailEnseignantElement;
    'detail-search': HTMLDetailSearchElement;
    'spi-candidat': HTMLSpiCandidatElement;
    'spi-formation': HTMLSpiFormationElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-login': HTMLSpiLoginElement;
    'spi-promotion': HTMLSpiPromotionElement;
    'spi-root': HTMLSpiRootElement;
    'spi-enseignant': HTMLSpiEnseignantElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
